# NUMPY

In [2]:
# Untuk mengimpor numpy
import numpy as np

In [3]:
# Untuk mengetahui versi numpy
np.__version__

'1.16.4'

In [4]:
# Untuk mengetahui kegunaan suatu method
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## ARRAY

In [5]:
# Membuat list pada python
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [6]:
# Operasi list
print(a+b)
print(a*b)

# List tidak bisa dioperasikan secara matematis

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In [8]:
# Membuat array dengan numpy
a_array = np.array(a)
b_array = np.array(b)

# Operasi array
print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


## LISTS

In [9]:
v = np.array([1,2,3])

v

array([1, 2, 3])

In [11]:
# Membuat matriks 3 kolom 2 baris
m = np.array([[1,2,3],[4,5,6]])

m

array([[1, 2, 3],
       [4, 5, 6]])

## Mengecek Tipe Data

In [13]:
# Mengecek tipe data array
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [14]:
a = [1,2,3]

type(a)

list

## Mengecek ukuran dan jumlah elemen

In [15]:
# Untuk mengecek ukuran array
v.shape

(3,)

In [16]:
# Untuk mengecek ukuran array
# Ukuran adalah 2 baris 3 kolom
m.shape

(2, 3)

In [17]:
# Untuk mengecek jumlah elemen
m.size

6

## Mengubah tipe data dalam array

In [18]:
# dtype untuk menihat tipe data dalam array
m.dtype

dtype('int32')

In [19]:
# dtype juga dapat digunakan untuk mengubah tipe data array
m = np.array([[1,2,3],[2,3,4]], dtype = float)

m

array([[1., 2., 3.],
       [2., 3., 4.]])

In [26]:
m.dtype

dtype('float64')

## Membuat matrix zero

In [20]:
# Membuat zero matrix
zero_matrix = np.zeros(5)
zero_matrix

array([0., 0., 0., 0., 0.])

In [22]:
zero_matrix2 = np.zeros((5,2))
zero_matrix2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Membuat matrix ones

In [23]:
# Membuat matrix ones
ones_matrix = np.ones(5)
ones_matrix

array([1., 1., 1., 1., 1.])

In [24]:
ones_matrix2 = np.ones((5,3,4))
ones_matrix2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
ones_matrix2.shape

(5, 3, 4)

## Membuat Matrix Tiga Dimensi

In [36]:
tri_d = np.array([
    [[1,2,3],        # 'Array' ini menunjukkan baris pertama
     [4,5,6],        # Baris == kolom tiga dimensi
     [7,8,9]],       # Kolom == kedalaman tiga dimensi
    
    [[10,11,12],     # Ini menunjukkan baris kedua
     [13,14,15],
     [16,17,18]]   
])

tri_d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# EXERCISE 1

1. Membuat matrix 4 baris 3 kolom dari list

In [28]:
list1 = [[1,2,3], 
         [4,5,6],
         [7,8,9],
         [10,11,12]]
matrix1= np.array(list1)
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

2. Membuat matriks tertera

In [29]:
matrix2 = np.array([[2,7,12,0],[3,9,3,4],[4,0,1,3]])
matrix2

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

3. Membuat matrix dengan ukuran (size) 10

In [31]:
matrix3 = np.ones((5,2))
matrix3

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

4. Membuat matriks ones dengan 2 baris, 3 kolom, 3 kedalaman

In [32]:
matrix4 = np.ones((2,3,3))
matrix4

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

5. Membuat array tertera dari zero arrays dan for loops

In [33]:
matrix5 = np.zeros((5,3))
for i in range(2):
    matrix5 = matrix5 + np.ones((5,3))
matrix5

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])